#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running pre-push hook"

# Build 실행 후 결과를 변수에 저장
build_output=$(npm run build)

# 빌드 결과 출력
echo "$build_output"

# 빌드에서 경고가 발생했는지 확인
if echo "$build_output" | grep -q 'Compiled with warnings'; then
  echo "Build contains warnings. Push rejected."
  exit 1
fi
